repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-merge-conflict

    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.1
      hooks:
          - id: isort
            stages: [commit, push]
            types: [python]
            language_version: python3

    - repo: https://github.com/PyCQA/flake8
      rev: 7.0.0
      hooks:
          - id: flake8
            stages: [commit, push]
            types: [python]
            language_version: python3

    - repo: https://github.com/python/black
      rev: 24.4.0
      hooks:
          - id: black
            stages: [commit, push]
            types: [python]
            language_version: python3
    - repo: local
      hooks:
          - id: tests
            name: run tests
            entry: cd producer && python3 -m unittest
            types: [python]
            stages: [commit, push]
            language: system
